---
# Without any seed particles
project: 
  - 7flat
replicas: 1
variable: T
values:
  - 0.122
  - 0.123
  - 0.124
  - 0.125
  - 0.126
  - 0.127
  - 0.128
  - 0.129
inputFiles: 
  - 7flat
outputFiles: "/home/gila/seeding"
sbatch: false
generateFiles:
  - false
  - true
account:
  - sulcgpu3
queue:
  - sulcgpu1
allocations:
  - 9999
cpuPerJob:
  - 1
gpuPerJob:
  - 0

sbatchLine: 8
...