---
# Without any seed particles
project: blank
replicas: 4
location: /scratch/sroy85/seeding
variable: T
values:
  - 0.122
  - 0.123
  - 0.124
  - 0.125
  - 0.126
  - 0.127
  - 0.128
  - 0.129
inputFiles: input
batches:
  account:
    - sulcgpu3
    - sulcgpu2
    - sulcgpu1
  queue:
    - sulcgpu1
    - sulcgpu1
    - sulcgpu1
  allocations:
    - 32
    - 28
    - 20

progressRepoter: progress.txt

...