---
# Without any seed particles
project: 
  - blank
  - large
replicas: 4
variable: T
values:
  - 0.122
  - 0.123
  - 0.124
  - 0.125
  - 0.126
  - 0.127
  - 0.128
  - 0.129
inputFiles: 
  - inputs
  - large
outputFiles: "/scratch/sroy85/seeding2"
generateFiles:
  - false
  - true
account:
  - sulcgpu3
  - sulcgpu2
  - sulcgpu1
queue:
  - sulcgpu1
  - sulcgpu1
  - sulcgpu1
allocations:
  - 32
  - 28
  - 20
cpuPerJob:
  - 1
  - 1
  - 1
gpuPerJob:
  - 0
  - 0
  - 0
sbatchLine: 8
...