---
# Without any seed particles
project: 
  - 5triangle
  # - 4ring
replicas: 4
# exec: "/scratch/sroy85/Software/oxDNA/build/bin/oxDNA_debug"
exec: "/home/gila/oxDNAold/build/bin"
variable: T
values:
  - 0.122
  - 0.123
  - 0.124
  - 0.125
  - 0.126
  - 0.127
  - 0.128
  - 0.129
inputFiles: 
  - 5triangle
  # - 4ring
outputFiles: "/scratch/sroy85/seeding"
sbatch: false
generateFiles:
  - true
  - true
account:
  - sulcgpu1
queue:
  - sulcgpu1
allocations:
  - 999
cpuPerJob:
  - 1
gpuPerJob:
  - 0

sbatchLine: 8
...

# Notes extralarge 3.8e7  4flat 2.41e7 large 4.64e7 7flat 1.58e7
