name: CMake Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.21'

      - name: Build project
        run: cmake --build . --config Release

      # - name: Run CMake tests
      #   run: ctest --output-on-failure
